// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/auth/v1/auth.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sysson/dink/sdk/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthPluginServiceName is the fully-qualified name of the AuthPluginService service.
	AuthPluginServiceName = "sdk.auth.v1.AuthPluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthPluginServiceAuthZReqProcedure is the fully-qualified name of the AuthPluginService's
	// AuthZReq RPC.
	AuthPluginServiceAuthZReqProcedure = "/sdk.auth.v1.AuthPluginService/AuthZReq"
	// AuthPluginServiceAuthZResProcedure is the fully-qualified name of the AuthPluginService's
	// AuthZRes RPC.
	AuthPluginServiceAuthZResProcedure = "/sdk.auth.v1.AuthPluginService/AuthZRes"
)

// AuthPluginServiceClient is a client for the sdk.auth.v1.AuthPluginService service.
type AuthPluginServiceClient interface {
	AuthZReq(context.Context, *v1.AuthZReqRequest) (*v1.AuthZReqResponse, error)
	AuthZRes(context.Context, *v1.AuthZResRequest) (*v1.AuthZResResponse, error)
}

// NewAuthPluginServiceClient constructs a client for the sdk.auth.v1.AuthPluginService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthPluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authPluginServiceMethods := v1.File_sdk_auth_v1_auth_proto.Services().ByName("AuthPluginService").Methods()
	return &authPluginServiceClient{
		authZReq: connect.NewClient[v1.AuthZReqRequest, v1.AuthZReqResponse](
			httpClient,
			baseURL+AuthPluginServiceAuthZReqProcedure,
			connect.WithSchema(authPluginServiceMethods.ByName("AuthZReq")),
			connect.WithClientOptions(opts...),
		),
		authZRes: connect.NewClient[v1.AuthZResRequest, v1.AuthZResResponse](
			httpClient,
			baseURL+AuthPluginServiceAuthZResProcedure,
			connect.WithSchema(authPluginServiceMethods.ByName("AuthZRes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authPluginServiceClient implements AuthPluginServiceClient.
type authPluginServiceClient struct {
	authZReq *connect.Client[v1.AuthZReqRequest, v1.AuthZReqResponse]
	authZRes *connect.Client[v1.AuthZResRequest, v1.AuthZResResponse]
}

// AuthZReq calls sdk.auth.v1.AuthPluginService.AuthZReq.
func (c *authPluginServiceClient) AuthZReq(ctx context.Context, req *v1.AuthZReqRequest) (*v1.AuthZReqResponse, error) {
	response, err := c.authZReq.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AuthZRes calls sdk.auth.v1.AuthPluginService.AuthZRes.
func (c *authPluginServiceClient) AuthZRes(ctx context.Context, req *v1.AuthZResRequest) (*v1.AuthZResResponse, error) {
	response, err := c.authZRes.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AuthPluginServiceHandler is an implementation of the sdk.auth.v1.AuthPluginService service.
type AuthPluginServiceHandler interface {
	AuthZReq(context.Context, *v1.AuthZReqRequest) (*v1.AuthZReqResponse, error)
	AuthZRes(context.Context, *v1.AuthZResRequest) (*v1.AuthZResResponse, error)
}

// NewAuthPluginServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthPluginServiceHandler(svc AuthPluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authPluginServiceMethods := v1.File_sdk_auth_v1_auth_proto.Services().ByName("AuthPluginService").Methods()
	authPluginServiceAuthZReqHandler := connect.NewUnaryHandlerSimple(
		AuthPluginServiceAuthZReqProcedure,
		svc.AuthZReq,
		connect.WithSchema(authPluginServiceMethods.ByName("AuthZReq")),
		connect.WithHandlerOptions(opts...),
	)
	authPluginServiceAuthZResHandler := connect.NewUnaryHandlerSimple(
		AuthPluginServiceAuthZResProcedure,
		svc.AuthZRes,
		connect.WithSchema(authPluginServiceMethods.ByName("AuthZRes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.auth.v1.AuthPluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthPluginServiceAuthZReqProcedure:
			authPluginServiceAuthZReqHandler.ServeHTTP(w, r)
		case AuthPluginServiceAuthZResProcedure:
			authPluginServiceAuthZResHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthPluginServiceHandler struct{}

func (UnimplementedAuthPluginServiceHandler) AuthZReq(context.Context, *v1.AuthZReqRequest) (*v1.AuthZReqResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.auth.v1.AuthPluginService.AuthZReq is not implemented"))
}

func (UnimplementedAuthPluginServiceHandler) AuthZRes(context.Context, *v1.AuthZResRequest) (*v1.AuthZResResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.auth.v1.AuthPluginService.AuthZRes is not implemented"))
}
