package translator

func (c *Cluster) Init()          {}
func (c *Cluster) Join()          {}
func (c *Cluster) Leave()         {}
func (c *Cluster) Inspect()       {}
func (c *Cluster) Update()        {}
func (c *Cluster) GetUnlockKey()  {}
func (c *Cluster) UnlockSwarm()   {}
func (c *Cluster) GetServices()   {}
func (c *Cluster) GetService()    {}
func (c *Cluster) CreateService() {}
func (c *Cluster) UpdateService() {}
func (c *Cluster) RemoveService() {}
func (c *Cluster) ServiceLogs()   {}
func (c *Cluster) GetNodes()      {}
func (c *Cluster) GetNode()       {}
func (c *Cluster) UpdateNode()    {}
func (c *Cluster) RemoveNode()    {}
func (c *Cluster) GetTasks()      {}
func (c *Cluster) GetTask()       {}
func (c *Cluster) GetSecrets()    {}
func (c *Cluster) CreateSecret()  {}
func (c *Cluster) RemoveSecret()  {}
func (c *Cluster) GetSecret()     {}
func (c *Cluster) UpdateSecret()  {}
func (c *Cluster) GetConfigs()    {}
func (c *Cluster) CreateConfig()  {}
func (c *Cluster) RemoveConfig()  {}
func (c *Cluster) GetConfig()     {}
func (c *Cluster) UpdateConfig()  {}
