// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: core/registry/api/v1/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity is the tenant a request is made for.
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Organization  string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	CommonName    string                 `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Anonymous     bool                   `protobuf:"varint,4,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Identity) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Identity) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Identity) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

// RegistryAuth is the credentials from a Docker client's X-Registry-Auth.
type RegistryAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IdentityToken string                 `protobuf:"bytes,3,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"`
	RegistryToken string                 `protobuf:"bytes,4,opt,name=registry_token,json=registryToken,proto3" json:"registry_token,omitempty"`
	ServerAddress string                 `protobuf:"bytes,5,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryAuth) Reset() {
	*x = RegistryAuth{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryAuth) ProtoMessage() {}

func (x *RegistryAuth) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryAuth.ProtoReflect.Descriptor instead.
func (*RegistryAuth) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistryAuth) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

func (x *RegistryAuth) GetRegistryToken() string {
	if x != nil {
		return x.RegistryToken
	}
	return ""
}

func (x *RegistryAuth) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Architecture  string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Variant       string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsFeatures    []string               `protobuf:"bytes,5,rep,name=os_features,json=osFeatures,proto3" json:"os_features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Platform) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *Platform) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Platform) GetOsFeatures() []string {
	if x != nil {
		return x.OsFeatures
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *RegistryAuth          `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetAuth() *RegistryAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityToken string                 `protobuf:"bytes,1,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

// Reference names an image in an upstream registry. With neither tag nor
// digest, every tag in the repository is pulled.
type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *Reference) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Reference) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Reference) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Reference) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type PullRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Identity  *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Reference *Reference             `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Auth      *RegistryAuth          `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// Headers to send upstream, from the Docker client's X-Meta-* headers.
	MetaHeaders   map[string]*HeaderValues `protobuf:"bytes,4,rep,name=meta_headers,json=metaHeaders,proto3" json:"meta_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platforms     []*Platform              `protobuf:"bytes,5,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *PullRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PullRequest) GetReference() *Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *PullRequest) GetAuth() *RegistryAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *PullRequest) GetMetaHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.MetaHeaders
	}
	return nil
}

func (x *PullRequest) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type PullResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One Docker JSON-stream progress message.
	Message       []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *PullResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ListImagesRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Descriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Platform      *Platform              `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *Descriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Descriptor) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Descriptor) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Descriptor) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

type ImageSummary struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags    []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	RepoDigests []string               `protobuf:"bytes,3,rep,name=repo_digests,json=repoDigests,proto3" json:"repo_digests,omitempty"`
	Created     int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Size        int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// What the image reference resolves to.
	Target        *Descriptor `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSummary) Reset() {
	*x = ImageSummary{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSummary) ProtoMessage() {}

func (x *ImageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSummary.ProtoReflect.Descriptor instead.
func (*ImageSummary) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *ImageSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageSummary) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageSummary) GetRepoDigests() []string {
	if x != nil {
		return x.RepoDigests
	}
	return nil
}

func (x *ImageSummary) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImageSummary) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageSummary) GetTarget() *Descriptor {
	if x != nil {
		return x.Target
	}
	return nil
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageSummary        `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ListImagesResponse) GetImages() []*ImageSummary {
	if x != nil {
		return x.Images
	}
	return nil
}

type InspectImageRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// The image name as given to docker inspect, relative to the namespace. A
	// tag, a digest reference or a full or truncated image ID.
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform *Platform `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// Include the per-manifest breakdown of a multi-platform image.
	Manifests     bool `protobuf:"varint,4,opt,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectImageRequest) Reset() {
	*x = InspectImageRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectImageRequest) ProtoMessage() {}

func (x *InspectImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectImageRequest.ProtoReflect.Descriptor instead.
func (*InspectImageRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{13}
}

func (x *InspectImageRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *InspectImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InspectImageRequest) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *InspectImageRequest) GetManifests() bool {
	if x != nil {
		return x.Manifests
	}
	return false
}

type InspectImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON-encoded image inspect document.
	Image         []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectImageResponse) Reset() {
	*x = InspectImageResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectImageResponse) ProtoMessage() {}

func (x *InspectImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectImageResponse.ProtoReflect.Descriptor instead.
func (*InspectImageResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *InspectImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type ImageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform      *Platform              `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageHistoryRequest) Reset() {
	*x = ImageHistoryRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHistoryRequest) ProtoMessage() {}

func (x *ImageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHistoryRequest.ProtoReflect.Descriptor instead.
func (*ImageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{15}
}

func (x *ImageHistoryRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ImageHistoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageHistoryRequest) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

type ImageHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON-encoded array of history items, newest first.
	History       []byte `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageHistoryResponse) Reset() {
	*x = ImageHistoryResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHistoryResponse) ProtoMessage() {}

func (x *ImageHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHistoryResponse.ProtoReflect.Descriptor instead.
func (*ImageHistoryResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ImageHistoryResponse) GetHistory() []byte {
	if x != nil {
		return x.History
	}
	return nil
}

type ImageAttestationsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform *Platform              `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// In-toto predicate types to return; empty returns every statement.
	PredicateTypes []string `protobuf:"bytes,4,rep,name=predicate_types,json=predicateTypes,proto3" json:"predicate_types,omitempty"`
	// Read the statement bodies out of storage and return them.
	IncludeStatement bool `protobuf:"varint,5,opt,name=include_statement,json=includeStatement,proto3" json:"include_statement,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImageAttestationsRequest) Reset() {
	*x = ImageAttestationsRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageAttestationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageAttestationsRequest) ProtoMessage() {}

func (x *ImageAttestationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageAttestationsRequest.ProtoReflect.Descriptor instead.
func (*ImageAttestationsRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *ImageAttestationsRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ImageAttestationsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageAttestationsRequest) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *ImageAttestationsRequest) GetPredicateTypes() []string {
	if x != nil {
		return x.PredicateTypes
	}
	return nil
}

func (x *ImageAttestationsRequest) GetIncludeStatement() bool {
	if x != nil {
		return x.IncludeStatement
	}
	return false
}

type ImageAttestationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON-encoded array of attestation statements.
	Statements    []byte `protobuf:"bytes,1,opt,name=statements,proto3" json:"statements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageAttestationsResponse) Reset() {
	*x = ImageAttestationsResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageAttestationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageAttestationsResponse) ProtoMessage() {}

func (x *ImageAttestationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageAttestationsResponse.ProtoReflect.Descriptor instead.
func (*ImageAttestationsResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{18}
}

func (x *ImageAttestationsResponse) GetStatements() []byte {
	if x != nil {
		return x.Statements
	}
	return nil
}

type RemoveImageRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// The image name as given to docker rmi, relative to the namespace.
	Name          string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platforms     []*Platform `protobuf:"bytes,3,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveImageRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RemoveImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveImageRequest) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type RemoveImageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Untagged      string                 `protobuf:"bytes,1,opt,name=untagged,proto3" json:"untagged,omitempty"`
	Deleted       string                 `protobuf:"bytes,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRecord) Reset() {
	*x = RemoveImageRecord{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRecord) ProtoMessage() {}

func (x *RemoveImageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRecord.ProtoReflect.Descriptor instead.
func (*RemoveImageRecord) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveImageRecord) GetUntagged() string {
	if x != nil {
		return x.Untagged
	}
	return ""
}

func (x *RemoveImageRecord) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RemoveImageRecord   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveImageResponse) GetRecords() []*RemoveImageRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type TagImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        *Reference             `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagImageRequest) Reset() {
	*x = TagImageRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagImageRequest) ProtoMessage() {}

func (x *TagImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagImageRequest.ProtoReflect.Descriptor instead.
func (*TagImageRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{22}
}

func (x *TagImageRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *TagImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagImageRequest) GetTarget() *Reference {
	if x != nil {
		return x.Target
	}
	return nil
}

type TagImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagImageResponse) Reset() {
	*x = TagImageResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagImageResponse) ProtoMessage() {}

func (x *TagImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagImageResponse.ProtoReflect.Descriptor instead.
func (*TagImageResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{23}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// JSON-encoded variables object.
	Variables     []byte `protobuf:"bytes,3,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{24}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *QueryRequest) GetVariables() []byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON-encoded GraphQL response ({"data": ..., "errors": ...}).
	Response      []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{25}
}

func (x *QueryResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type IssuePullCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePullCredentialRequest) Reset() {
	*x = IssuePullCredentialRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePullCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePullCredentialRequest) ProtoMessage() {}

func (x *IssuePullCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePullCredentialRequest.ProtoReflect.Descriptor instead.
func (*IssuePullCredentialRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{26}
}

func (x *IssuePullCredentialRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type IssuePullCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePullCredentialResponse) Reset() {
	*x = IssuePullCredentialResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePullCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePullCredentialResponse) ProtoMessage() {}

func (x *IssuePullCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePullCredentialResponse.ProtoReflect.Descriptor instead.
func (*IssuePullCredentialResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{27}
}

func (x *IssuePullCredentialResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IssuePullCredentialResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RevokePullCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePullCredentialRequest) Reset() {
	*x = RevokePullCredentialRequest{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePullCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePullCredentialRequest) ProtoMessage() {}

func (x *RevokePullCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePullCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokePullCredentialRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{28}
}

func (x *RevokePullCredentialRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type RevokePullCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePullCredentialResponse) Reset() {
	*x = RevokePullCredentialResponse{}
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePullCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePullCredentialResponse) ProtoMessage() {}

func (x *RevokePullCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_api_v1_registry_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePullCredentialResponse.ProtoReflect.Descriptor instead.
func (*RevokePullCredentialResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_api_v1_registry_proto_rawDescGZIP(), []int{29}
}

var File_core_registry_api_v1_registry_proto protoreflect.FileDescriptor

const file_core_registry_api_v1_registry_proto_rawDesc = "" +
	"\n" +
	"#core/registry/api/v1/registry.proto\x12\x14core.registry.api.v1\"\x8b\x01\n" +
	"\bIdentity\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12\x1c\n" +
	"\tanonymous\x18\x04 \x01(\bR\tanonymous\"\xbb\x01\n" +
	"\fRegistryAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eidentity_token\x18\x03 \x01(\tR\ridentityToken\x12%\n" +
	"\x0eregistry_token\x18\x04 \x01(\tR\rregistryToken\x12%\n" +
	"\x0eserver_address\x18\x05 \x01(\tR\rserverAddress\"\x98\x01\n" +
	"\bPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vos_features\x18\x05 \x03(\tR\n" +
	"osFeatures\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"F\n" +
	"\fLoginRequest\x126\n" +
	"\x04auth\x18\x01 \x01(\v2\".core.registry.api.v1.RegistryAuthR\x04auth\"6\n" +
	"\rLoginResponse\x12%\n" +
	"\x0eidentity_token\x18\x01 \x01(\tR\ridentityToken\"i\n" +
	"\tReference\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\xb9\x03\n" +
	"\vPullRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\x12=\n" +
	"\treference\x18\x02 \x01(\v2\x1f.core.registry.api.v1.ReferenceR\treference\x126\n" +
	"\x04auth\x18\x03 \x01(\v2\".core.registry.api.v1.RegistryAuthR\x04auth\x12U\n" +
	"\fmeta_headers\x18\x04 \x03(\v22.core.registry.api.v1.PullRequest.MetaHeadersEntryR\vmetaHeaders\x12<\n" +
	"\tplatforms\x18\x05 \x03(\v2\x1e.core.registry.api.v1.PlatformR\tplatforms\x1ab\n" +
	"\x10MetaHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".core.registry.api.v1.HeaderValuesR\x05value:\x028\x01\"(\n" +
	"\fPullResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"O\n" +
	"\x11ListImagesRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\"\x93\x01\n" +
	"\n" +
	"Descriptor\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12:\n" +
	"\bplatform\x18\x04 \x01(\v2\x1e.core.registry.api.v1.PlatformR\bplatform\"\xc6\x01\n" +
	"\fImageSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12!\n" +
	"\frepo_digests\x18\x03 \x03(\tR\vrepoDigests\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x128\n" +
	"\x06target\x18\x06 \x01(\v2 .core.registry.api.v1.DescriptorR\x06target\"P\n" +
	"\x12ListImagesResponse\x12:\n" +
	"\x06images\x18\x01 \x03(\v2\".core.registry.api.v1.ImageSummaryR\x06images\"\xbf\x01\n" +
	"\x13InspectImageRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\bplatform\x18\x03 \x01(\v2\x1e.core.registry.api.v1.PlatformR\bplatform\x12\x1c\n" +
	"\tmanifests\x18\x04 \x01(\bR\tmanifests\",\n" +
	"\x14InspectImageResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"\xa1\x01\n" +
	"\x13ImageHistoryRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\bplatform\x18\x03 \x01(\v2\x1e.core.registry.api.v1.PlatformR\bplatform\"0\n" +
	"\x14ImageHistoryResponse\x12\x18\n" +
	"\ahistory\x18\x01 \x01(\fR\ahistory\"\xfc\x01\n" +
	"\x18ImageAttestationsRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\bplatform\x18\x03 \x01(\v2\x1e.core.registry.api.v1.PlatformR\bplatform\x12'\n" +
	"\x0fpredicate_types\x18\x04 \x03(\tR\x0epredicateTypes\x12+\n" +
	"\x11include_statement\x18\x05 \x01(\bR\x10includeStatement\";\n" +
	"\x19ImageAttestationsResponse\x12\x1e\n" +
	"\n" +
	"statements\x18\x01 \x01(\fR\n" +
	"statements\"\xa2\x01\n" +
	"\x12RemoveImageRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\tplatforms\x18\x03 \x03(\v2\x1e.core.registry.api.v1.PlatformR\tplatforms\"I\n" +
	"\x11RemoveImageRecord\x12\x1a\n" +
	"\buntagged\x18\x01 \x01(\tR\buntagged\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\tR\adeleted\"X\n" +
	"\x13RemoveImageResponse\x12A\n" +
	"\arecords\x18\x01 \x03(\v2'.core.registry.api.v1.RemoveImageRecordR\arecords\"\x9a\x01\n" +
	"\x0fTagImageRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\x06target\x18\x03 \x01(\v2\x1f.core.registry.api.v1.ReferenceR\x06target\"\x12\n" +
	"\x10TagImageResponse\"i\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12\x1c\n" +
	"\tvariables\x18\x03 \x01(\fR\tvariables\"+\n" +
	"\rQueryResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"X\n" +
	"\x1aIssuePullCredentialRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\"U\n" +
	"\x1bIssuePullCredentialResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\x1bRevokePullCredentialRequest\x12:\n" +
	"\bidentity\x18\x01 \x01(\v2\x1e.core.registry.api.v1.IdentityR\bidentity\"\x1e\n" +
	"\x1cRevokePullCredentialResponse2\xe5\b\n" +
	"\x0fRegistryService\x12P\n" +
	"\x05Login\x12\".core.registry.api.v1.LoginRequest\x1a#.core.registry.api.v1.LoginResponse\x12O\n" +
	"\x04Pull\x12!.core.registry.api.v1.PullRequest\x1a\".core.registry.api.v1.PullResponse0\x01\x12_\n" +
	"\n" +
	"ListImages\x12'.core.registry.api.v1.ListImagesRequest\x1a(.core.registry.api.v1.ListImagesResponse\x12e\n" +
	"\fInspectImage\x12).core.registry.api.v1.InspectImageRequest\x1a*.core.registry.api.v1.InspectImageResponse\x12e\n" +
	"\fImageHistory\x12).core.registry.api.v1.ImageHistoryRequest\x1a*.core.registry.api.v1.ImageHistoryResponse\x12t\n" +
	"\x11ImageAttestations\x12..core.registry.api.v1.ImageAttestationsRequest\x1a/.core.registry.api.v1.ImageAttestationsResponse\x12b\n" +
	"\vRemoveImage\x12(.core.registry.api.v1.RemoveImageRequest\x1a).core.registry.api.v1.RemoveImageResponse\x12Y\n" +
	"\bTagImage\x12%.core.registry.api.v1.TagImageRequest\x1a&.core.registry.api.v1.TagImageResponse\x12P\n" +
	"\x05Query\x12\".core.registry.api.v1.QueryRequest\x1a#.core.registry.api.v1.QueryResponse\x12z\n" +
	"\x13IssuePullCredential\x120.core.registry.api.v1.IssuePullCredentialRequest\x1a1.core.registry.api.v1.IssuePullCredentialResponse\x12}\n" +
	"\x14RevokePullCredential\x121.core.registry.api.v1.RevokePullCredentialRequest\x1a2.core.registry.api.v1.RevokePullCredentialResponseB\xd2\x01\n" +
	"\x18com.core.registry.api.v1B\rRegistryProtoP\x01Z4github.com/sysson/dink/core/registry/api/v1;registry\xa2\x02\x03CRA\xaa\x02\x14Core.Registry.Api.V1\xca\x02\x14Core\\Registry\\Api\\V1\xe2\x02 Core\\Registry\\Api\\V1\\GPBMetadata\xea\x02\x17Core::Registry::Api::V1b\x06proto3"

var (
	file_core_registry_api_v1_registry_proto_rawDescOnce sync.Once
	file_core_registry_api_v1_registry_proto_rawDescData []byte
)

func file_core_registry_api_v1_registry_proto_rawDescGZIP() []byte {
	file_core_registry_api_v1_registry_proto_rawDescOnce.Do(func() {
		file_core_registry_api_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_registry_api_v1_registry_proto_rawDesc), len(file_core_registry_api_v1_registry_proto_rawDesc)))
	})
	return file_core_registry_api_v1_registry_proto_rawDescData
}

var file_core_registry_api_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_core_registry_api_v1_registry_proto_goTypes = []any{
	(*Identity)(nil),                     // 0: core.registry.api.v1.Identity
	(*RegistryAuth)(nil),                 // 1: core.registry.api.v1.RegistryAuth
	(*Platform)(nil),                     // 2: core.registry.api.v1.Platform
	(*HeaderValues)(nil),                 // 3: core.registry.api.v1.HeaderValues
	(*LoginRequest)(nil),                 // 4: core.registry.api.v1.LoginRequest
	(*LoginResponse)(nil),                // 5: core.registry.api.v1.LoginResponse
	(*Reference)(nil),                    // 6: core.registry.api.v1.Reference
	(*PullRequest)(nil),                  // 7: core.registry.api.v1.PullRequest
	(*PullResponse)(nil),                 // 8: core.registry.api.v1.PullResponse
	(*ListImagesRequest)(nil),            // 9: core.registry.api.v1.ListImagesRequest
	(*Descriptor)(nil),                   // 10: core.registry.api.v1.Descriptor
	(*ImageSummary)(nil),                 // 11: core.registry.api.v1.ImageSummary
	(*ListImagesResponse)(nil),           // 12: core.registry.api.v1.ListImagesResponse
	(*InspectImageRequest)(nil),          // 13: core.registry.api.v1.InspectImageRequest
	(*InspectImageResponse)(nil),         // 14: core.registry.api.v1.InspectImageResponse
	(*ImageHistoryRequest)(nil),          // 15: core.registry.api.v1.ImageHistoryRequest
	(*ImageHistoryResponse)(nil),         // 16: core.registry.api.v1.ImageHistoryResponse
	(*ImageAttestationsRequest)(nil),     // 17: core.registry.api.v1.ImageAttestationsRequest
	(*ImageAttestationsResponse)(nil),    // 18: core.registry.api.v1.ImageAttestationsResponse
	(*RemoveImageRequest)(nil),           // 19: core.registry.api.v1.RemoveImageRequest
	(*RemoveImageRecord)(nil),            // 20: core.registry.api.v1.RemoveImageRecord
	(*RemoveImageResponse)(nil),          // 21: core.registry.api.v1.RemoveImageResponse
	(*TagImageRequest)(nil),              // 22: core.registry.api.v1.TagImageRequest
	(*TagImageResponse)(nil),             // 23: core.registry.api.v1.TagImageResponse
	(*QueryRequest)(nil),                 // 24: core.registry.api.v1.QueryRequest
	(*QueryResponse)(nil),                // 25: core.registry.api.v1.QueryResponse
	(*IssuePullCredentialRequest)(nil),   // 26: core.registry.api.v1.IssuePullCredentialRequest
	(*IssuePullCredentialResponse)(nil),  // 27: core.registry.api.v1.IssuePullCredentialResponse
	(*RevokePullCredentialRequest)(nil),  // 28: core.registry.api.v1.RevokePullCredentialRequest
	(*RevokePullCredentialResponse)(nil), // 29: core.registry.api.v1.RevokePullCredentialResponse
	nil,                                  // 30: core.registry.api.v1.PullRequest.MetaHeadersEntry
}
var file_core_registry_api_v1_registry_proto_depIdxs = []int32{
	1,  // 0: core.registry.api.v1.LoginRequest.auth:type_name -> core.registry.api.v1.RegistryAuth
	0,  // 1: core.registry.api.v1.PullRequest.identity:type_name -> core.registry.api.v1.Identity
	6,  // 2: core.registry.api.v1.PullRequest.reference:type_name -> core.registry.api.v1.Reference
	1,  // 3: core.registry.api.v1.PullRequest.auth:type_name -> core.registry.api.v1.RegistryAuth
	30, // 4: core.registry.api.v1.PullRequest.meta_headers:type_name -> core.registry.api.v1.PullRequest.MetaHeadersEntry
	2,  // 5: core.registry.api.v1.PullRequest.platforms:type_name -> core.registry.api.v1.Platform
	0,  // 6: core.registry.api.v1.ListImagesRequest.identity:type_name -> core.registry.api.v1.Identity
	2,  // 7: core.registry.api.v1.Descriptor.platform:type_name -> core.registry.api.v1.Platform
	10, // 8: core.registry.api.v1.ImageSummary.target:type_name -> core.registry.api.v1.Descriptor
	11, // 9: core.registry.api.v1.ListImagesResponse.images:type_name -> core.registry.api.v1.ImageSummary
	0,  // 10: core.registry.api.v1.InspectImageRequest.identity:type_name -> core.registry.api.v1.Identity
	2,  // 11: core.registry.api.v1.InspectImageRequest.platform:type_name -> core.registry.api.v1.Platform
	0,  // 12: core.registry.api.v1.ImageHistoryRequest.identity:type_name -> core.registry.api.v1.Identity
	2,  // 13: core.registry.api.v1.ImageHistoryRequest.platform:type_name -> core.registry.api.v1.Platform
	0,  // 14: core.registry.api.v1.ImageAttestationsRequest.identity:type_name -> core.registry.api.v1.Identity
	2,  // 15: core.registry.api.v1.ImageAttestationsRequest.platform:type_name -> core.registry.api.v1.Platform
	0,  // 16: core.registry.api.v1.RemoveImageRequest.identity:type_name -> core.registry.api.v1.Identity
	2,  // 17: core.registry.api.v1.RemoveImageRequest.platforms:type_name -> core.registry.api.v1.Platform
	20, // 18: core.registry.api.v1.RemoveImageResponse.records:type_name -> core.registry.api.v1.RemoveImageRecord
	0,  // 19: core.registry.api.v1.TagImageRequest.identity:type_name -> core.registry.api.v1.Identity
	6,  // 20: core.registry.api.v1.TagImageRequest.target:type_name -> core.registry.api.v1.Reference
	0,  // 21: core.registry.api.v1.IssuePullCredentialRequest.identity:type_name -> core.registry.api.v1.Identity
	0,  // 22: core.registry.api.v1.RevokePullCredentialRequest.identity:type_name -> core.registry.api.v1.Identity
	3,  // 23: core.registry.api.v1.PullRequest.MetaHeadersEntry.value:type_name -> core.registry.api.v1.HeaderValues
	4,  // 24: core.registry.api.v1.RegistryService.Login:input_type -> core.registry.api.v1.LoginRequest
	7,  // 25: core.registry.api.v1.RegistryService.Pull:input_type -> core.registry.api.v1.PullRequest
	9,  // 26: core.registry.api.v1.RegistryService.ListImages:input_type -> core.registry.api.v1.ListImagesRequest
	13, // 27: core.registry.api.v1.RegistryService.InspectImage:input_type -> core.registry.api.v1.InspectImageRequest
	15, // 28: core.registry.api.v1.RegistryService.ImageHistory:input_type -> core.registry.api.v1.ImageHistoryRequest
	17, // 29: core.registry.api.v1.RegistryService.ImageAttestations:input_type -> core.registry.api.v1.ImageAttestationsRequest
	19, // 30: core.registry.api.v1.RegistryService.RemoveImage:input_type -> core.registry.api.v1.RemoveImageRequest
	22, // 31: core.registry.api.v1.RegistryService.TagImage:input_type -> core.registry.api.v1.TagImageRequest
	24, // 32: core.registry.api.v1.RegistryService.Query:input_type -> core.registry.api.v1.QueryRequest
	26, // 33: core.registry.api.v1.RegistryService.IssuePullCredential:input_type -> core.registry.api.v1.IssuePullCredentialRequest
	28, // 34: core.registry.api.v1.RegistryService.RevokePullCredential:input_type -> core.registry.api.v1.RevokePullCredentialRequest
	5,  // 35: core.registry.api.v1.RegistryService.Login:output_type -> core.registry.api.v1.LoginResponse
	8,  // 36: core.registry.api.v1.RegistryService.Pull:output_type -> core.registry.api.v1.PullResponse
	12, // 37: core.registry.api.v1.RegistryService.ListImages:output_type -> core.registry.api.v1.ListImagesResponse
	14, // 38: core.registry.api.v1.RegistryService.InspectImage:output_type -> core.registry.api.v1.InspectImageResponse
	16, // 39: core.registry.api.v1.RegistryService.ImageHistory:output_type -> core.registry.api.v1.ImageHistoryResponse
	18, // 40: core.registry.api.v1.RegistryService.ImageAttestations:output_type -> core.registry.api.v1.ImageAttestationsResponse
	21, // 41: core.registry.api.v1.RegistryService.RemoveImage:output_type -> core.registry.api.v1.RemoveImageResponse
	23, // 42: core.registry.api.v1.RegistryService.TagImage:output_type -> core.registry.api.v1.TagImageResponse
	25, // 43: core.registry.api.v1.RegistryService.Query:output_type -> core.registry.api.v1.QueryResponse
	27, // 44: core.registry.api.v1.RegistryService.IssuePullCredential:output_type -> core.registry.api.v1.IssuePullCredentialResponse
	29, // 45: core.registry.api.v1.RegistryService.RevokePullCredential:output_type -> core.registry.api.v1.RevokePullCredentialResponse
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_core_registry_api_v1_registry_proto_init() }
func file_core_registry_api_v1_registry_proto_init() {
	if File_core_registry_api_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_registry_api_v1_registry_proto_rawDesc), len(file_core_registry_api_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_registry_api_v1_registry_proto_goTypes,
		DependencyIndexes: file_core_registry_api_v1_registry_proto_depIdxs,
		MessageInfos:      file_core_registry_api_v1_registry_proto_msgTypes,
	}.Build()
	File_core_registry_api_v1_registry_proto = out.File
	file_core_registry_api_v1_registry_proto_goTypes = nil
	file_core_registry_api_v1_registry_proto_depIdxs = nil
}
