version: 2
project_name: dinkle

builds:
  - id: dinkle
    main: ./cmd/dinkle
    binary: dinkle
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  prerelease: auto
