// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/registry/v1/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity is the tenant a request is made for.
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Organization  string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	CommonName    string                 `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Anonymous     bool                   `protobuf:"varint,4,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Identity) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Identity) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Identity) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

// RegistryAuth is the credentials from a Docker client's X-Registry-Auth.
type RegistryAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IdentityToken string                 `protobuf:"bytes,3,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"`
	RegistryToken string                 `protobuf:"bytes,4,opt,name=registry_token,json=registryToken,proto3" json:"registry_token,omitempty"`
	ServerAddress string                 `protobuf:"bytes,5,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryAuth) Reset() {
	*x = RegistryAuth{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryAuth) ProtoMessage() {}

func (x *RegistryAuth) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryAuth.ProtoReflect.Descriptor instead.
func (*RegistryAuth) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistryAuth) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

func (x *RegistryAuth) GetRegistryToken() string {
	if x != nil {
		return x.RegistryToken
	}
	return ""
}

func (x *RegistryAuth) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Architecture  string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Variant       string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsFeatures    []string               `protobuf:"bytes,5,rep,name=os_features,json=osFeatures,proto3" json:"os_features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Platform) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *Platform) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Platform) GetOsFeatures() []string {
	if x != nil {
		return x.OsFeatures
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *RegistryAuth          `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetAuth() *RegistryAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityToken string                 `protobuf:"bytes,1,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

// Reference names an image in an upstream registry. With neither tag nor
// digest, every tag in the repository is pulled.
type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *Reference) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Reference) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Reference) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Reference) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type PullRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Identity  *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Reference *Reference             `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Auth      *RegistryAuth          `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// Headers to send upstream, from the Docker client's X-Meta-* headers.
	MetaHeaders   map[string]*HeaderValues `protobuf:"bytes,4,rep,name=meta_headers,json=metaHeaders,proto3" json:"meta_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platforms     []*Platform              `protobuf:"bytes,5,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *PullRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PullRequest) GetReference() *Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *PullRequest) GetAuth() *RegistryAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *PullRequest) GetMetaHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.MetaHeaders
	}
	return nil
}

func (x *PullRequest) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type PullResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One Docker JSON-stream progress message.
	Message       []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *PullResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ListImagesRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Descriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Platform      *Platform              `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *Descriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Descriptor) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Descriptor) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Descriptor) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

type ImageSummary struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags    []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	RepoDigests []string               `protobuf:"bytes,3,rep,name=repo_digests,json=repoDigests,proto3" json:"repo_digests,omitempty"`
	Created     int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Size        int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// What the image reference resolves to.
	Target        *Descriptor `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSummary) Reset() {
	*x = ImageSummary{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSummary) ProtoMessage() {}

func (x *ImageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSummary.ProtoReflect.Descriptor instead.
func (*ImageSummary) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *ImageSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageSummary) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageSummary) GetRepoDigests() []string {
	if x != nil {
		return x.RepoDigests
	}
	return nil
}

func (x *ImageSummary) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImageSummary) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageSummary) GetTarget() *Descriptor {
	if x != nil {
		return x.Target
	}
	return nil
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageSummary        `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ListImagesResponse) GetImages() []*ImageSummary {
	if x != nil {
		return x.Images
	}
	return nil
}

type RemoveImageRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// The image name as given to docker rmi, relative to the namespace.
	Name          string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platforms     []*Platform `protobuf:"bytes,3,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveImageRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RemoveImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveImageRequest) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type RemoveImageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Untagged      string                 `protobuf:"bytes,1,opt,name=untagged,proto3" json:"untagged,omitempty"`
	Deleted       string                 `protobuf:"bytes,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRecord) Reset() {
	*x = RemoveImageRecord{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRecord) ProtoMessage() {}

func (x *RemoveImageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRecord.ProtoReflect.Descriptor instead.
func (*RemoveImageRecord) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveImageRecord) GetUntagged() string {
	if x != nil {
		return x.Untagged
	}
	return ""
}

func (x *RemoveImageRecord) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RemoveImageRecord   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveImageResponse) GetRecords() []*RemoveImageRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// JSON-encoded variables object.
	Variables     []byte `protobuf:"bytes,3,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *QueryRequest) GetVariables() []byte {
	if x != nil {
		return x.Variables
	}
	return nil
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON-encoded GraphQL response ({"data": ..., "errors": ...}).
	Response      []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_registry_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sdk_registry_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *QueryResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_sdk_registry_v1_registry_proto protoreflect.FileDescriptor

const file_sdk_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1esdk/registry/v1/registry.proto\x12\x0fsdk.registry.v1\"\x8b\x01\n" +
	"\bIdentity\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12\x1c\n" +
	"\tanonymous\x18\x04 \x01(\bR\tanonymous\"\xbb\x01\n" +
	"\fRegistryAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eidentity_token\x18\x03 \x01(\tR\ridentityToken\x12%\n" +
	"\x0eregistry_token\x18\x04 \x01(\tR\rregistryToken\x12%\n" +
	"\x0eserver_address\x18\x05 \x01(\tR\rserverAddress\"\x98\x01\n" +
	"\bPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vos_features\x18\x05 \x03(\tR\n" +
	"osFeatures\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"A\n" +
	"\fLoginRequest\x121\n" +
	"\x04auth\x18\x01 \x01(\v2\x1d.sdk.registry.v1.RegistryAuthR\x04auth\"6\n" +
	"\rLoginResponse\x12%\n" +
	"\x0eidentity_token\x18\x01 \x01(\tR\ridentityToken\"i\n" +
	"\tReference\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\x9b\x03\n" +
	"\vPullRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\v2\x19.sdk.registry.v1.IdentityR\bidentity\x128\n" +
	"\treference\x18\x02 \x01(\v2\x1a.sdk.registry.v1.ReferenceR\treference\x121\n" +
	"\x04auth\x18\x03 \x01(\v2\x1d.sdk.registry.v1.RegistryAuthR\x04auth\x12P\n" +
	"\fmeta_headers\x18\x04 \x03(\v2-.sdk.registry.v1.PullRequest.MetaHeadersEntryR\vmetaHeaders\x127\n" +
	"\tplatforms\x18\x05 \x03(\v2\x19.sdk.registry.v1.PlatformR\tplatforms\x1a]\n" +
	"\x10MetaHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.sdk.registry.v1.HeaderValuesR\x05value:\x028\x01\"(\n" +
	"\fPullResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"J\n" +
	"\x11ListImagesRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\v2\x19.sdk.registry.v1.IdentityR\bidentity\"\x8e\x01\n" +
	"\n" +
	"Descriptor\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x125\n" +
	"\bplatform\x18\x04 \x01(\v2\x19.sdk.registry.v1.PlatformR\bplatform\"\xc1\x01\n" +
	"\fImageSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12!\n" +
	"\frepo_digests\x18\x03 \x03(\tR\vrepoDigests\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x123\n" +
	"\x06target\x18\x06 \x01(\v2\x1b.sdk.registry.v1.DescriptorR\x06target\"K\n" +
	"\x12ListImagesResponse\x125\n" +
	"\x06images\x18\x01 \x03(\v2\x1d.sdk.registry.v1.ImageSummaryR\x06images\"\x98\x01\n" +
	"\x12RemoveImageRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\v2\x19.sdk.registry.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\tplatforms\x18\x03 \x03(\v2\x19.sdk.registry.v1.PlatformR\tplatforms\"I\n" +
	"\x11RemoveImageRecord\x12\x1a\n" +
	"\buntagged\x18\x01 \x01(\tR\buntagged\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\tR\adeleted\"S\n" +
	"\x13RemoveImageResponse\x12<\n" +
	"\arecords\x18\x01 \x03(\v2\".sdk.registry.v1.RemoveImageRecordR\arecords\"i\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12\x1c\n" +
	"\tvariables\x18\x03 \x01(\fR\tvariables\"+\n" +
	"\rQueryResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse2\x99\x03\n" +
	"\x0fRegistryService\x12F\n" +
	"\x05Login\x12\x1d.sdk.registry.v1.LoginRequest\x1a\x1e.sdk.registry.v1.LoginResponse\x12E\n" +
	"\x04Pull\x12\x1c.sdk.registry.v1.PullRequest\x1a\x1d.sdk.registry.v1.PullResponse0\x01\x12U\n" +
	"\n" +
	"ListImages\x12\".sdk.registry.v1.ListImagesRequest\x1a#.sdk.registry.v1.ListImagesResponse\x12X\n" +
	"\vRemoveImage\x12#.sdk.registry.v1.RemoveImageRequest\x1a$.sdk.registry.v1.RemoveImageResponse\x12F\n" +
	"\x05Query\x12\x1d.sdk.registry.v1.QueryRequest\x1a\x1e.sdk.registry.v1.QueryResponseB\xb3\x01\n" +
	"\x13com.sdk.registry.v1B\rRegistryProtoP\x01Z/github.com/sysson/dink/sdk/registry/v1;registry\xa2\x02\x03SRX\xaa\x02\x0fSdk.Registry.V1\xca\x02\x0fSdk\\Registry\\V1\xe2\x02\x1bSdk\\Registry\\V1\\GPBMetadata\xea\x02\x11Sdk::Registry::V1b\x06proto3"

var (
	file_sdk_registry_v1_registry_proto_rawDescOnce sync.Once
	file_sdk_registry_v1_registry_proto_rawDescData []byte
)

func file_sdk_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_sdk_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_sdk_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_registry_v1_registry_proto_rawDesc), len(file_sdk_registry_v1_registry_proto_rawDesc)))
	})
	return file_sdk_registry_v1_registry_proto_rawDescData
}

var file_sdk_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_sdk_registry_v1_registry_proto_goTypes = []any{
	(*Identity)(nil),            // 0: sdk.registry.v1.Identity
	(*RegistryAuth)(nil),        // 1: sdk.registry.v1.RegistryAuth
	(*Platform)(nil),            // 2: sdk.registry.v1.Platform
	(*HeaderValues)(nil),        // 3: sdk.registry.v1.HeaderValues
	(*LoginRequest)(nil),        // 4: sdk.registry.v1.LoginRequest
	(*LoginResponse)(nil),       // 5: sdk.registry.v1.LoginResponse
	(*Reference)(nil),           // 6: sdk.registry.v1.Reference
	(*PullRequest)(nil),         // 7: sdk.registry.v1.PullRequest
	(*PullResponse)(nil),        // 8: sdk.registry.v1.PullResponse
	(*ListImagesRequest)(nil),   // 9: sdk.registry.v1.ListImagesRequest
	(*Descriptor)(nil),          // 10: sdk.registry.v1.Descriptor
	(*ImageSummary)(nil),        // 11: sdk.registry.v1.ImageSummary
	(*ListImagesResponse)(nil),  // 12: sdk.registry.v1.ListImagesResponse
	(*RemoveImageRequest)(nil),  // 13: sdk.registry.v1.RemoveImageRequest
	(*RemoveImageRecord)(nil),   // 14: sdk.registry.v1.RemoveImageRecord
	(*RemoveImageResponse)(nil), // 15: sdk.registry.v1.RemoveImageResponse
	(*QueryRequest)(nil),        // 16: sdk.registry.v1.QueryRequest
	(*QueryResponse)(nil),       // 17: sdk.registry.v1.QueryResponse
	nil,                         // 18: sdk.registry.v1.PullRequest.MetaHeadersEntry
}
var file_sdk_registry_v1_registry_proto_depIdxs = []int32{
	1,  // 0: sdk.registry.v1.LoginRequest.auth:type_name -> sdk.registry.v1.RegistryAuth
	0,  // 1: sdk.registry.v1.PullRequest.identity:type_name -> sdk.registry.v1.Identity
	6,  // 2: sdk.registry.v1.PullRequest.reference:type_name -> sdk.registry.v1.Reference
	1,  // 3: sdk.registry.v1.PullRequest.auth:type_name -> sdk.registry.v1.RegistryAuth
	18, // 4: sdk.registry.v1.PullRequest.meta_headers:type_name -> sdk.registry.v1.PullRequest.MetaHeadersEntry
	2,  // 5: sdk.registry.v1.PullRequest.platforms:type_name -> sdk.registry.v1.Platform
	0,  // 6: sdk.registry.v1.ListImagesRequest.identity:type_name -> sdk.registry.v1.Identity
	2,  // 7: sdk.registry.v1.Descriptor.platform:type_name -> sdk.registry.v1.Platform
	10, // 8: sdk.registry.v1.ImageSummary.target:type_name -> sdk.registry.v1.Descriptor
	11, // 9: sdk.registry.v1.ListImagesResponse.images:type_name -> sdk.registry.v1.ImageSummary
	0,  // 10: sdk.registry.v1.RemoveImageRequest.identity:type_name -> sdk.registry.v1.Identity
	2,  // 11: sdk.registry.v1.RemoveImageRequest.platforms:type_name -> sdk.registry.v1.Platform
	14, // 12: sdk.registry.v1.RemoveImageResponse.records:type_name -> sdk.registry.v1.RemoveImageRecord
	3,  // 13: sdk.registry.v1.PullRequest.MetaHeadersEntry.value:type_name -> sdk.registry.v1.HeaderValues
	4,  // 14: sdk.registry.v1.RegistryService.Login:input_type -> sdk.registry.v1.LoginRequest
	7,  // 15: sdk.registry.v1.RegistryService.Pull:input_type -> sdk.registry.v1.PullRequest
	9,  // 16: sdk.registry.v1.RegistryService.ListImages:input_type -> sdk.registry.v1.ListImagesRequest
	13, // 17: sdk.registry.v1.RegistryService.RemoveImage:input_type -> sdk.registry.v1.RemoveImageRequest
	16, // 18: sdk.registry.v1.RegistryService.Query:input_type -> sdk.registry.v1.QueryRequest
	5,  // 19: sdk.registry.v1.RegistryService.Login:output_type -> sdk.registry.v1.LoginResponse
	8,  // 20: sdk.registry.v1.RegistryService.Pull:output_type -> sdk.registry.v1.PullResponse
	12, // 21: sdk.registry.v1.RegistryService.ListImages:output_type -> sdk.registry.v1.ListImagesResponse
	15, // 22: sdk.registry.v1.RegistryService.RemoveImage:output_type -> sdk.registry.v1.RemoveImageResponse
	17, // 23: sdk.registry.v1.RegistryService.Query:output_type -> sdk.registry.v1.QueryResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sdk_registry_v1_registry_proto_init() }
func file_sdk_registry_v1_registry_proto_init() {
	if File_sdk_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_registry_v1_registry_proto_rawDesc), len(file_sdk_registry_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_sdk_registry_v1_registry_proto_depIdxs,
		MessageInfos:      file_sdk_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_sdk_registry_v1_registry_proto = out.File
	file_sdk_registry_v1_registry_proto_goTypes = nil
	file_sdk_registry_v1_registry_proto_depIdxs = nil
}
