// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/volumes/v1/volumes.proto

package volumes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityName  string                 `protobuf:"bytes,1,opt,name=identity_name,json=identityName,proto3" json:"identity_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_sdk_volumes_v1_volumes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetIdentityName() string {
	if x != nil {
		return x.IdentityName
	}
	return ""
}

func (x *CreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StorageClassName string                 `protobuf:"bytes,1,opt,name=storage_class_name,json=storageClassName,proto3" json:"storage_class_name,omitempty"`
	// size is a Kubernetes quantity such as "10Gi"; empty uses dink's default.
	Size string `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	// access_modes are Kubernetes access modes such as "ReadWriteOnce"; empty means ReadWriteOnce.
	AccessModes   []string          `protobuf:"bytes,3,rep,name=access_modes,json=accessModes,proto3" json:"access_modes,omitempty"`
	Annotations   map[string]string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_sdk_volumes_v1_volumes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetStorageClassName() string {
	if x != nil {
		return x.StorageClassName
	}
	return ""
}

func (x *CreateResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CreateResponse) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *CreateResponse) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityName  string                 `protobuf:"bytes,1,opt,name=identity_name,json=identityName,proto3" json:"identity_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_sdk_volumes_v1_volumes_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRequest) GetIdentityName() string {
	if x != nil {
		return x.IdentityName
	}
	return ""
}

func (x *RemoveRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_volumes_v1_volumes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_sdk_volumes_v1_volumes_proto_rawDescGZIP(), []int{3}
}

var File_sdk_volumes_v1_volumes_proto protoreflect.FileDescriptor

const file_sdk_volumes_v1_volumes_proto_rawDesc = "" +
	"\n" +
	"\x1csdk/volumes/v1/volumes.proto\x12\x0esdk.volumes.v1\"\xe6\x02\n" +
	"\rCreateRequest\x12#\n" +
	"\ridentity_name\x18\x01 \x01(\tR\fidentityName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12D\n" +
	"\aoptions\x18\x04 \x03(\v2*.sdk.volumes.v1.CreateRequest.OptionsEntryR\aoptions\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).sdk.volumes.v1.CreateRequest.LabelsEntryR\x06labels\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\x0eCreateResponse\x12,\n" +
	"\x12storage_class_name\x18\x01 \x01(\tR\x10storageClassName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12!\n" +
	"\faccess_modes\x18\x03 \x03(\tR\vaccessModes\x12Q\n" +
	"\vannotations\x18\x04 \x03(\v2/.sdk.volumes.v1.CreateResponse.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\rRemoveRequest\x12#\n" +
	"\ridentity_name\x18\x01 \x01(\tR\fidentityName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12D\n" +
	"\aoptions\x18\x04 \x03(\v2*.sdk.volumes.v1.RemoveRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eRemoveResponse2\xa7\x01\n" +
	"\x13VolumePluginService\x12G\n" +
	"\x06Create\x12\x1d.sdk.volumes.v1.CreateRequest\x1a\x1e.sdk.volumes.v1.CreateResponse\x12G\n" +
	"\x06Remove\x12\x1d.sdk.volumes.v1.RemoveRequest\x1a\x1e.sdk.volumes.v1.RemoveResponseB\xab\x01\n" +
	"\x12com.sdk.volumes.v1B\fVolumesProtoP\x01Z-github.com/sysson/dink/sdk/volumes/v1;volumes\xa2\x02\x03SVX\xaa\x02\x0eSdk.Volumes.V1\xca\x02\x0eSdk\\Volumes\\V1\xe2\x02\x1aSdk\\Volumes\\V1\\GPBMetadata\xea\x02\x10Sdk::Volumes::V1b\x06proto3"

var (
	file_sdk_volumes_v1_volumes_proto_rawDescOnce sync.Once
	file_sdk_volumes_v1_volumes_proto_rawDescData []byte
)

func file_sdk_volumes_v1_volumes_proto_rawDescGZIP() []byte {
	file_sdk_volumes_v1_volumes_proto_rawDescOnce.Do(func() {
		file_sdk_volumes_v1_volumes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_volumes_v1_volumes_proto_rawDesc), len(file_sdk_volumes_v1_volumes_proto_rawDesc)))
	})
	return file_sdk_volumes_v1_volumes_proto_rawDescData
}

var file_sdk_volumes_v1_volumes_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sdk_volumes_v1_volumes_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: sdk.volumes.v1.CreateRequest
	(*CreateResponse)(nil), // 1: sdk.volumes.v1.CreateResponse
	(*RemoveRequest)(nil),  // 2: sdk.volumes.v1.RemoveRequest
	(*RemoveResponse)(nil), // 3: sdk.volumes.v1.RemoveResponse
	nil,                    // 4: sdk.volumes.v1.CreateRequest.OptionsEntry
	nil,                    // 5: sdk.volumes.v1.CreateRequest.LabelsEntry
	nil,                    // 6: sdk.volumes.v1.CreateResponse.AnnotationsEntry
	nil,                    // 7: sdk.volumes.v1.RemoveRequest.OptionsEntry
}
var file_sdk_volumes_v1_volumes_proto_depIdxs = []int32{
	4, // 0: sdk.volumes.v1.CreateRequest.options:type_name -> sdk.volumes.v1.CreateRequest.OptionsEntry
	5, // 1: sdk.volumes.v1.CreateRequest.labels:type_name -> sdk.volumes.v1.CreateRequest.LabelsEntry
	6, // 2: sdk.volumes.v1.CreateResponse.annotations:type_name -> sdk.volumes.v1.CreateResponse.AnnotationsEntry
	7, // 3: sdk.volumes.v1.RemoveRequest.options:type_name -> sdk.volumes.v1.RemoveRequest.OptionsEntry
	0, // 4: sdk.volumes.v1.VolumePluginService.Create:input_type -> sdk.volumes.v1.CreateRequest
	2, // 5: sdk.volumes.v1.VolumePluginService.Remove:input_type -> sdk.volumes.v1.RemoveRequest
	1, // 6: sdk.volumes.v1.VolumePluginService.Create:output_type -> sdk.volumes.v1.CreateResponse
	3, // 7: sdk.volumes.v1.VolumePluginService.Remove:output_type -> sdk.volumes.v1.RemoveResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sdk_volumes_v1_volumes_proto_init() }
func file_sdk_volumes_v1_volumes_proto_init() {
	if File_sdk_volumes_v1_volumes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_volumes_v1_volumes_proto_rawDesc), len(file_sdk_volumes_v1_volumes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_volumes_v1_volumes_proto_goTypes,
		DependencyIndexes: file_sdk_volumes_v1_volumes_proto_depIdxs,
		MessageInfos:      file_sdk_volumes_v1_volumes_proto_msgTypes,
	}.Build()
	File_sdk_volumes_v1_volumes_proto = out.File
	file_sdk_volumes_v1_volumes_proto_goTypes = nil
	file_sdk_volumes_v1_volumes_proto_depIdxs = nil
}
