// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/registry/v1/registry.proto

package registryconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sysson/dink/sdk/registry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RegistryServiceName is the fully-qualified name of the RegistryService service.
	RegistryServiceName = "sdk.registry.v1.RegistryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RegistryServiceLoginProcedure is the fully-qualified name of the RegistryService's Login RPC.
	RegistryServiceLoginProcedure = "/sdk.registry.v1.RegistryService/Login"
	// RegistryServicePullProcedure is the fully-qualified name of the RegistryService's Pull RPC.
	RegistryServicePullProcedure = "/sdk.registry.v1.RegistryService/Pull"
	// RegistryServiceListImagesProcedure is the fully-qualified name of the RegistryService's
	// ListImages RPC.
	RegistryServiceListImagesProcedure = "/sdk.registry.v1.RegistryService/ListImages"
	// RegistryServiceRemoveImageProcedure is the fully-qualified name of the RegistryService's
	// RemoveImage RPC.
	RegistryServiceRemoveImageProcedure = "/sdk.registry.v1.RegistryService/RemoveImage"
	// RegistryServiceQueryProcedure is the fully-qualified name of the RegistryService's Query RPC.
	RegistryServiceQueryProcedure = "/sdk.registry.v1.RegistryService/Query"
)

// RegistryServiceClient is a client for the sdk.registry.v1.RegistryService service.
type RegistryServiceClient interface {
	// Login verifies credentials against a registry. Nothing is persisted.
	Login(context.Context, *v1.LoginRequest) (*v1.LoginResponse, error)
	// Pull copies an image from its upstream registry into dinki, streaming
	// Docker JSON-stream progress messages.
	Pull(context.Context, *v1.PullRequest) (*connect.ServerStreamForClient[v1.PullResponse], error)
	// ListImages lists the images in the caller's namespace.
	ListImages(context.Context, *v1.ListImagesRequest) (*v1.ListImagesResponse, error)
	// RemoveImage untags an image and, when nothing else uses it, removes its
	// manifests and blobs from the repository. Garbage collection reclaims
	// content that is no longer referenced anywhere.
	RemoveImage(context.Context, *v1.RemoveImageRequest) (*v1.RemoveImageResponse, error)
	// Query executes a read-only GraphQL document against dinki metadata.
	Query(context.Context, *v1.QueryRequest) (*v1.QueryResponse, error)
}

// NewRegistryServiceClient constructs a client for the sdk.registry.v1.RegistryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRegistryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RegistryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	registryServiceMethods := v1.File_sdk_registry_v1_registry_proto.Services().ByName("RegistryService").Methods()
	return &registryServiceClient{
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+RegistryServiceLoginProcedure,
			connect.WithSchema(registryServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		pull: connect.NewClient[v1.PullRequest, v1.PullResponse](
			httpClient,
			baseURL+RegistryServicePullProcedure,
			connect.WithSchema(registryServiceMethods.ByName("Pull")),
			connect.WithClientOptions(opts...),
		),
		listImages: connect.NewClient[v1.ListImagesRequest, v1.ListImagesResponse](
			httpClient,
			baseURL+RegistryServiceListImagesProcedure,
			connect.WithSchema(registryServiceMethods.ByName("ListImages")),
			connect.WithClientOptions(opts...),
		),
		removeImage: connect.NewClient[v1.RemoveImageRequest, v1.RemoveImageResponse](
			httpClient,
			baseURL+RegistryServiceRemoveImageProcedure,
			connect.WithSchema(registryServiceMethods.ByName("RemoveImage")),
			connect.WithClientOptions(opts...),
		),
		query: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+RegistryServiceQueryProcedure,
			connect.WithSchema(registryServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
	}
}

// registryServiceClient implements RegistryServiceClient.
type registryServiceClient struct {
	login       *connect.Client[v1.LoginRequest, v1.LoginResponse]
	pull        *connect.Client[v1.PullRequest, v1.PullResponse]
	listImages  *connect.Client[v1.ListImagesRequest, v1.ListImagesResponse]
	removeImage *connect.Client[v1.RemoveImageRequest, v1.RemoveImageResponse]
	query       *connect.Client[v1.QueryRequest, v1.QueryResponse]
}

// Login calls sdk.registry.v1.RegistryService.Login.
func (c *registryServiceClient) Login(ctx context.Context, req *v1.LoginRequest) (*v1.LoginResponse, error) {
	response, err := c.login.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Pull calls sdk.registry.v1.RegistryService.Pull.
func (c *registryServiceClient) Pull(ctx context.Context, req *v1.PullRequest) (*connect.ServerStreamForClient[v1.PullResponse], error) {
	return c.pull.CallServerStream(ctx, connect.NewRequest(req))
}

// ListImages calls sdk.registry.v1.RegistryService.ListImages.
func (c *registryServiceClient) ListImages(ctx context.Context, req *v1.ListImagesRequest) (*v1.ListImagesResponse, error) {
	response, err := c.listImages.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RemoveImage calls sdk.registry.v1.RegistryService.RemoveImage.
func (c *registryServiceClient) RemoveImage(ctx context.Context, req *v1.RemoveImageRequest) (*v1.RemoveImageResponse, error) {
	response, err := c.removeImage.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Query calls sdk.registry.v1.RegistryService.Query.
func (c *registryServiceClient) Query(ctx context.Context, req *v1.QueryRequest) (*v1.QueryResponse, error) {
	response, err := c.query.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RegistryServiceHandler is an implementation of the sdk.registry.v1.RegistryService service.
type RegistryServiceHandler interface {
	// Login verifies credentials against a registry. Nothing is persisted.
	Login(context.Context, *v1.LoginRequest) (*v1.LoginResponse, error)
	// Pull copies an image from its upstream registry into dinki, streaming
	// Docker JSON-stream progress messages.
	Pull(context.Context, *v1.PullRequest, *connect.ServerStream[v1.PullResponse]) error
	// ListImages lists the images in the caller's namespace.
	ListImages(context.Context, *v1.ListImagesRequest) (*v1.ListImagesResponse, error)
	// RemoveImage untags an image and, when nothing else uses it, removes its
	// manifests and blobs from the repository. Garbage collection reclaims
	// content that is no longer referenced anywhere.
	RemoveImage(context.Context, *v1.RemoveImageRequest) (*v1.RemoveImageResponse, error)
	// Query executes a read-only GraphQL document against dinki metadata.
	Query(context.Context, *v1.QueryRequest) (*v1.QueryResponse, error)
}

// NewRegistryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRegistryServiceHandler(svc RegistryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	registryServiceMethods := v1.File_sdk_registry_v1_registry_proto.Services().ByName("RegistryService").Methods()
	registryServiceLoginHandler := connect.NewUnaryHandlerSimple(
		RegistryServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(registryServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	registryServicePullHandler := connect.NewServerStreamHandlerSimple(
		RegistryServicePullProcedure,
		svc.Pull,
		connect.WithSchema(registryServiceMethods.ByName("Pull")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceListImagesHandler := connect.NewUnaryHandlerSimple(
		RegistryServiceListImagesProcedure,
		svc.ListImages,
		connect.WithSchema(registryServiceMethods.ByName("ListImages")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceRemoveImageHandler := connect.NewUnaryHandlerSimple(
		RegistryServiceRemoveImageProcedure,
		svc.RemoveImage,
		connect.WithSchema(registryServiceMethods.ByName("RemoveImage")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceQueryHandler := connect.NewUnaryHandlerSimple(
		RegistryServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(registryServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.registry.v1.RegistryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RegistryServiceLoginProcedure:
			registryServiceLoginHandler.ServeHTTP(w, r)
		case RegistryServicePullProcedure:
			registryServicePullHandler.ServeHTTP(w, r)
		case RegistryServiceListImagesProcedure:
			registryServiceListImagesHandler.ServeHTTP(w, r)
		case RegistryServiceRemoveImageProcedure:
			registryServiceRemoveImageHandler.ServeHTTP(w, r)
		case RegistryServiceQueryProcedure:
			registryServiceQueryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRegistryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRegistryServiceHandler struct{}

func (UnimplementedRegistryServiceHandler) Login(context.Context, *v1.LoginRequest) (*v1.LoginResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.registry.v1.RegistryService.Login is not implemented"))
}

func (UnimplementedRegistryServiceHandler) Pull(context.Context, *v1.PullRequest, *connect.ServerStream[v1.PullResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sdk.registry.v1.RegistryService.Pull is not implemented"))
}

func (UnimplementedRegistryServiceHandler) ListImages(context.Context, *v1.ListImagesRequest) (*v1.ListImagesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.registry.v1.RegistryService.ListImages is not implemented"))
}

func (UnimplementedRegistryServiceHandler) RemoveImage(context.Context, *v1.RemoveImageRequest) (*v1.RemoveImageResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.registry.v1.RegistryService.RemoveImage is not implemented"))
}

func (UnimplementedRegistryServiceHandler) Query(context.Context, *v1.QueryRequest) (*v1.QueryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.registry.v1.RegistryService.Query is not implemented"))
}
