// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/plugin/v1/plugin.proto

package pluginconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sysson/dink/sdk/plugin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginServiceName is the fully-qualified name of the PluginService service.
	PluginServiceName = "sdk.plugin.v1.PluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginServiceInfoProcedure is the fully-qualified name of the PluginService's Info RPC.
	PluginServiceInfoProcedure = "/sdk.plugin.v1.PluginService/Info"
)

// PluginServiceClient is a client for the sdk.plugin.v1.PluginService service.
type PluginServiceClient interface {
	Info(context.Context, *v1.InfoRequest) (*v1.InfoResponse, error)
}

// NewPluginServiceClient constructs a client for the sdk.plugin.v1.PluginService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginServiceMethods := v1.File_sdk_plugin_v1_plugin_proto.Services().ByName("PluginService").Methods()
	return &pluginServiceClient{
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+PluginServiceInfoProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginServiceClient implements PluginServiceClient.
type pluginServiceClient struct {
	info *connect.Client[v1.InfoRequest, v1.InfoResponse]
}

// Info calls sdk.plugin.v1.PluginService.Info.
func (c *pluginServiceClient) Info(ctx context.Context, req *v1.InfoRequest) (*v1.InfoResponse, error) {
	response, err := c.info.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// PluginServiceHandler is an implementation of the sdk.plugin.v1.PluginService service.
type PluginServiceHandler interface {
	Info(context.Context, *v1.InfoRequest) (*v1.InfoResponse, error)
}

// NewPluginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginServiceHandler(svc PluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginServiceMethods := v1.File_sdk_plugin_v1_plugin_proto.Services().ByName("PluginService").Methods()
	pluginServiceInfoHandler := connect.NewUnaryHandlerSimple(
		PluginServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(pluginServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.plugin.v1.PluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginServiceInfoProcedure:
			pluginServiceInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginServiceHandler struct{}

func (UnimplementedPluginServiceHandler) Info(context.Context, *v1.InfoRequest) (*v1.InfoResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.plugin.v1.PluginService.Info is not implemented"))
}
