// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/volumes/v1/volumes.proto

package volumesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sysson/dink/sdk/volumes/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VolumePluginServiceName is the fully-qualified name of the VolumePluginService service.
	VolumePluginServiceName = "sdk.volumes.v1.VolumePluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VolumePluginServiceCreateProcedure is the fully-qualified name of the VolumePluginService's
	// Create RPC.
	VolumePluginServiceCreateProcedure = "/sdk.volumes.v1.VolumePluginService/Create"
	// VolumePluginServiceRemoveProcedure is the fully-qualified name of the VolumePluginService's
	// Remove RPC.
	VolumePluginServiceRemoveProcedure = "/sdk.volumes.v1.VolumePluginService/Remove"
)

// VolumePluginServiceClient is a client for the sdk.volumes.v1.VolumePluginService service.
type VolumePluginServiceClient interface {
	Create(context.Context, *v1.CreateRequest) (*v1.CreateResponse, error)
	// Remove is called before dink deletes the claim, so the plugin can release external state.
	Remove(context.Context, *v1.RemoveRequest) (*v1.RemoveResponse, error)
}

// NewVolumePluginServiceClient constructs a client for the sdk.volumes.v1.VolumePluginService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVolumePluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VolumePluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	volumePluginServiceMethods := v1.File_sdk_volumes_v1_volumes_proto.Services().ByName("VolumePluginService").Methods()
	return &volumePluginServiceClient{
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+VolumePluginServiceCreateProcedure,
			connect.WithSchema(volumePluginServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[v1.RemoveRequest, v1.RemoveResponse](
			httpClient,
			baseURL+VolumePluginServiceRemoveProcedure,
			connect.WithSchema(volumePluginServiceMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
	}
}

// volumePluginServiceClient implements VolumePluginServiceClient.
type volumePluginServiceClient struct {
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
	remove *connect.Client[v1.RemoveRequest, v1.RemoveResponse]
}

// Create calls sdk.volumes.v1.VolumePluginService.Create.
func (c *volumePluginServiceClient) Create(ctx context.Context, req *v1.CreateRequest) (*v1.CreateResponse, error) {
	response, err := c.create.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Remove calls sdk.volumes.v1.VolumePluginService.Remove.
func (c *volumePluginServiceClient) Remove(ctx context.Context, req *v1.RemoveRequest) (*v1.RemoveResponse, error) {
	response, err := c.remove.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// VolumePluginServiceHandler is an implementation of the sdk.volumes.v1.VolumePluginService
// service.
type VolumePluginServiceHandler interface {
	Create(context.Context, *v1.CreateRequest) (*v1.CreateResponse, error)
	// Remove is called before dink deletes the claim, so the plugin can release external state.
	Remove(context.Context, *v1.RemoveRequest) (*v1.RemoveResponse, error)
}

// NewVolumePluginServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVolumePluginServiceHandler(svc VolumePluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	volumePluginServiceMethods := v1.File_sdk_volumes_v1_volumes_proto.Services().ByName("VolumePluginService").Methods()
	volumePluginServiceCreateHandler := connect.NewUnaryHandlerSimple(
		VolumePluginServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(volumePluginServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	volumePluginServiceRemoveHandler := connect.NewUnaryHandlerSimple(
		VolumePluginServiceRemoveProcedure,
		svc.Remove,
		connect.WithSchema(volumePluginServiceMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.volumes.v1.VolumePluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VolumePluginServiceCreateProcedure:
			volumePluginServiceCreateHandler.ServeHTTP(w, r)
		case VolumePluginServiceRemoveProcedure:
			volumePluginServiceRemoveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVolumePluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVolumePluginServiceHandler struct{}

func (UnimplementedVolumePluginServiceHandler) Create(context.Context, *v1.CreateRequest) (*v1.CreateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.volumes.v1.VolumePluginService.Create is not implemented"))
}

func (UnimplementedVolumePluginServiceHandler) Remove(context.Context, *v1.RemoveRequest) (*v1.RemoveResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.volumes.v1.VolumePluginService.Remove is not implemented"))
}
