// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/secrets/v1/secrets.proto

package secretsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sysson/dink/sdk/secrets/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecretsPluginServiceName is the fully-qualified name of the SecretsPluginService service.
	SecretsPluginServiceName = "sdk.secrets.v1.SecretsPluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecretsPluginServiceResolveProcedure is the fully-qualified name of the SecretsPluginService's
	// Resolve RPC.
	SecretsPluginServiceResolveProcedure = "/sdk.secrets.v1.SecretsPluginService/Resolve"
)

// SecretsPluginServiceClient is a client for the sdk.secrets.v1.SecretsPluginService service.
type SecretsPluginServiceClient interface {
	Resolve(context.Context, *v1.ResolveRequest) (*v1.ResolveResponse, error)
}

// NewSecretsPluginServiceClient constructs a client for the sdk.secrets.v1.SecretsPluginService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretsPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretsPluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secretsPluginServiceMethods := v1.File_sdk_secrets_v1_secrets_proto.Services().ByName("SecretsPluginService").Methods()
	return &secretsPluginServiceClient{
		resolve: connect.NewClient[v1.ResolveRequest, v1.ResolveResponse](
			httpClient,
			baseURL+SecretsPluginServiceResolveProcedure,
			connect.WithSchema(secretsPluginServiceMethods.ByName("Resolve")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secretsPluginServiceClient implements SecretsPluginServiceClient.
type secretsPluginServiceClient struct {
	resolve *connect.Client[v1.ResolveRequest, v1.ResolveResponse]
}

// Resolve calls sdk.secrets.v1.SecretsPluginService.Resolve.
func (c *secretsPluginServiceClient) Resolve(ctx context.Context, req *v1.ResolveRequest) (*v1.ResolveResponse, error) {
	response, err := c.resolve.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SecretsPluginServiceHandler is an implementation of the sdk.secrets.v1.SecretsPluginService
// service.
type SecretsPluginServiceHandler interface {
	Resolve(context.Context, *v1.ResolveRequest) (*v1.ResolveResponse, error)
}

// NewSecretsPluginServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretsPluginServiceHandler(svc SecretsPluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretsPluginServiceMethods := v1.File_sdk_secrets_v1_secrets_proto.Services().ByName("SecretsPluginService").Methods()
	secretsPluginServiceResolveHandler := connect.NewUnaryHandlerSimple(
		SecretsPluginServiceResolveProcedure,
		svc.Resolve,
		connect.WithSchema(secretsPluginServiceMethods.ByName("Resolve")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.secrets.v1.SecretsPluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretsPluginServiceResolveProcedure:
			secretsPluginServiceResolveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretsPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretsPluginServiceHandler struct{}

func (UnimplementedSecretsPluginServiceHandler) Resolve(context.Context, *v1.ResolveRequest) (*v1.ResolveResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.secrets.v1.SecretsPluginService.Resolve is not implemented"))
}
