apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dink.yaml
images:
  - name: ghcr.io/sysson/dink
    newTag: dev

configMapGenerator:
  - name: dink-config
    namespace: dink-system
    files:
      - config.json
    options:
      labels:
        app.kubernetes.io/name: dink
