apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dink.yaml
  - dinki.yaml
  - dinki-node.yaml
images:
  - name: ghcr.io/sysson/dink
    newTag: sha-8be2aa5d6b78e104f4ac05fd50b3af2ae9e9a700
  - name: ghcr.io/sysson/dinki
    newTag: sha-8be2aa5d6b78e104f4ac05fd50b3af2ae9e9a700
configMapGenerator:
  - name: dink-config
    namespace: dink-system
    files:
      - config.json
    options:
      labels:
        app.kubernetes.io/name: dink
  - name: dinki-config
    namespace: dink-system
    files:
      - config.json=dinki-config.json
    options:
      labels:
        app.kubernetes.io/name: dinki
        app.kubernetes.io/component: registry
