// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/secrets/v1/secrets.proto

package secrets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	IdentityName  string                   `protobuf:"bytes,1,opt,name=identity_name,json=identityName,proto3" json:"identity_name,omitempty"`
	Namespace     string                   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Ref           []*ResolveRequest_Secret `protobuf:"bytes,3,rep,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_sdk_secrets_v1_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetIdentityName() string {
	if x != nil {
		return x.IdentityName
	}
	return ""
}

func (x *ResolveRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResolveRequest) GetRef() []*ResolveRequest_Secret {
	if x != nil {
		return x.Ref
	}
	return nil
}

type ResolveResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Secret        []*ResolveResponse_Secret `protobuf:"bytes,1,rep,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_sdk_secrets_v1_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetSecret() []*ResolveResponse_Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ResolveRequest_Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest_Secret) Reset() {
	*x = ResolveRequest_Secret{}
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest_Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest_Secret) ProtoMessage() {}

func (x *ResolveRequest_Secret) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest_Secret.ProtoReflect.Descriptor instead.
func (*ResolveRequest_Secret) Descriptor() ([]byte, []int) {
	return file_sdk_secrets_v1_secrets_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResolveRequest_Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveRequest_Secret) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ResolveResponse_Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse_Secret) Reset() {
	*x = ResolveResponse_Secret{}
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse_Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse_Secret) ProtoMessage() {}

func (x *ResolveResponse_Secret) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_secrets_v1_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse_Secret.ProtoReflect.Descriptor instead.
func (*ResolveResponse_Secret) Descriptor() ([]byte, []int) {
	return file_sdk_secrets_v1_secrets_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResolveResponse_Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveResponse_Secret) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResolveResponse_Secret) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sdk_secrets_v1_secrets_proto protoreflect.FileDescriptor

const file_sdk_secrets_v1_secrets_proto_rawDesc = "" +
	"\n" +
	"\x1csdk/secrets/v1/secrets.proto\x12\x0esdk.secrets.v1\"\xbc\x01\n" +
	"\x0eResolveRequest\x12#\n" +
	"\ridentity_name\x18\x01 \x01(\tR\fidentityName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x127\n" +
	"\x03ref\x18\x03 \x03(\v2%.sdk.secrets.v1.ResolveRequest.SecretR\x03ref\x1a.\n" +
	"\x06Secret\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"\x9b\x01\n" +
	"\x0fResolveResponse\x12>\n" +
	"\x06secret\x18\x01 \x03(\v2&.sdk.secrets.v1.ResolveResponse.SecretR\x06secret\x1aH\n" +
	"\x06Secret\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2b\n" +
	"\x14SecretsPluginService\x12J\n" +
	"\aResolve\x12\x1e.sdk.secrets.v1.ResolveRequest\x1a\x1f.sdk.secrets.v1.ResolveResponseB\xab\x01\n" +
	"\x12com.sdk.secrets.v1B\fSecretsProtoP\x01Z-github.com/sysson/dink/sdk/secrets/v1;secrets\xa2\x02\x03SSX\xaa\x02\x0eSdk.Secrets.V1\xca\x02\x0eSdk\\Secrets\\V1\xe2\x02\x1aSdk\\Secrets\\V1\\GPBMetadata\xea\x02\x10Sdk::Secrets::V1b\x06proto3"

var (
	file_sdk_secrets_v1_secrets_proto_rawDescOnce sync.Once
	file_sdk_secrets_v1_secrets_proto_rawDescData []byte
)

func file_sdk_secrets_v1_secrets_proto_rawDescGZIP() []byte {
	file_sdk_secrets_v1_secrets_proto_rawDescOnce.Do(func() {
		file_sdk_secrets_v1_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_secrets_v1_secrets_proto_rawDesc), len(file_sdk_secrets_v1_secrets_proto_rawDesc)))
	})
	return file_sdk_secrets_v1_secrets_proto_rawDescData
}

var file_sdk_secrets_v1_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sdk_secrets_v1_secrets_proto_goTypes = []any{
	(*ResolveRequest)(nil),         // 0: sdk.secrets.v1.ResolveRequest
	(*ResolveResponse)(nil),        // 1: sdk.secrets.v1.ResolveResponse
	(*ResolveRequest_Secret)(nil),  // 2: sdk.secrets.v1.ResolveRequest.Secret
	(*ResolveResponse_Secret)(nil), // 3: sdk.secrets.v1.ResolveResponse.Secret
}
var file_sdk_secrets_v1_secrets_proto_depIdxs = []int32{
	2, // 0: sdk.secrets.v1.ResolveRequest.ref:type_name -> sdk.secrets.v1.ResolveRequest.Secret
	3, // 1: sdk.secrets.v1.ResolveResponse.secret:type_name -> sdk.secrets.v1.ResolveResponse.Secret
	0, // 2: sdk.secrets.v1.SecretsPluginService.Resolve:input_type -> sdk.secrets.v1.ResolveRequest
	1, // 3: sdk.secrets.v1.SecretsPluginService.Resolve:output_type -> sdk.secrets.v1.ResolveResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sdk_secrets_v1_secrets_proto_init() }
func file_sdk_secrets_v1_secrets_proto_init() {
	if File_sdk_secrets_v1_secrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_secrets_v1_secrets_proto_rawDesc), len(file_sdk_secrets_v1_secrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_secrets_v1_secrets_proto_goTypes,
		DependencyIndexes: file_sdk_secrets_v1_secrets_proto_depIdxs,
		MessageInfos:      file_sdk_secrets_v1_secrets_proto_msgTypes,
	}.Build()
	File_sdk_secrets_v1_secrets_proto = out.File
	file_sdk_secrets_v1_secrets_proto_goTypes = nil
	file_sdk_secrets_v1_secrets_proto_depIdxs = nil
}
