// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: secrets/v1/secrets.proto

package secrets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsPluginService_Resolve_FullMethodName = "/dink.secrets.v1.SecretsPluginService/Resolve"
)

// SecretsPluginServiceClient is the client API for SecretsPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecretsPluginServiceClient interface {
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type secretsPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsPluginServiceClient(cc grpc.ClientConnInterface) SecretsPluginServiceClient {
	return &secretsPluginServiceClient{cc}
}

func (c *secretsPluginServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, SecretsPluginService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsPluginServiceServer is the server API for SecretsPluginService service.
// All implementations must embed UnimplementedSecretsPluginServiceServer
// for forward compatibility.
type SecretsPluginServiceServer interface {
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	mustEmbedUnimplementedSecretsPluginServiceServer()
}

// UnimplementedSecretsPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsPluginServiceServer struct{}

func (UnimplementedSecretsPluginServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedSecretsPluginServiceServer) mustEmbedUnimplementedSecretsPluginServiceServer() {}
func (UnimplementedSecretsPluginServiceServer) testEmbeddedByValue()                              {}

// UnsafeSecretsPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsPluginServiceServer will
// result in compilation errors.
type UnsafeSecretsPluginServiceServer interface {
	mustEmbedUnimplementedSecretsPluginServiceServer()
}

func RegisterSecretsPluginServiceServer(s grpc.ServiceRegistrar, srv SecretsPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretsPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsPluginService_ServiceDesc, srv)
}

func _SecretsPluginService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsPluginServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsPluginService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsPluginServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsPluginService_ServiceDesc is the grpc.ServiceDesc for SecretsPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dink.secrets.v1.SecretsPluginService",
	HandlerType: (*SecretsPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _SecretsPluginService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secrets/v1/secrets.proto",
}
