// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/plugin/v1/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED PluginType = 0
	PluginType_PLUGIN_TYPE_AUTH        PluginType = 1
	PluginType_PLUGIN_TYPE_SECRETS     PluginType = 2
	PluginType_PLUGIN_TYPE_VOLUMES     PluginType = 3
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_UNSPECIFIED",
		1: "PLUGIN_TYPE_AUTH",
		2: "PLUGIN_TYPE_SECRETS",
		3: "PLUGIN_TYPE_VOLUMES",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED": 0,
		"PLUGIN_TYPE_AUTH":        1,
		"PLUGIN_TYPE_SECRETS":     2,
		"PLUGIN_TYPE_VOLUMES":     3,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_sdk_plugin_v1_plugin_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_sdk_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// api_version is the SDK plugin API version the plugin was built against.
	ApiVersion    uint32       `protobuf:"varint,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Types         []PluginType `protobuf:"varint,4,rep,packed,name=types,proto3,enum=sdk.plugin.v1.PluginType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_sdk_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_sdk_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *InfoResponse) GetTypes() []PluginType {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_sdk_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_sdk_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1asdk/plugin/v1/plugin.proto\x12\rsdk.plugin.v1\"\r\n" +
	"\vInfoRequest\"\x8e\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\rR\n" +
	"apiVersion\x12/\n" +
	"\x05types\x18\x04 \x03(\x0e2\x19.sdk.plugin.v1.PluginTypeR\x05types*q\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PLUGIN_TYPE_AUTH\x10\x01\x12\x17\n" +
	"\x13PLUGIN_TYPE_SECRETS\x10\x02\x12\x17\n" +
	"\x13PLUGIN_TYPE_VOLUMES\x10\x032P\n" +
	"\rPluginService\x12?\n" +
	"\x04Info\x12\x1a.sdk.plugin.v1.InfoRequest\x1a\x1b.sdk.plugin.v1.InfoResponseB\xa3\x01\n" +
	"\x11com.sdk.plugin.v1B\vPluginProtoP\x01Z+github.com/sysson/dink/sdk/plugin/v1;plugin\xa2\x02\x03SPX\xaa\x02\rSdk.Plugin.V1\xca\x02\rSdk\\Plugin\\V1\xe2\x02\x19Sdk\\Plugin\\V1\\GPBMetadata\xea\x02\x0fSdk::Plugin::V1b\x06proto3"

var (
	file_sdk_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_sdk_plugin_v1_plugin_proto_rawDescData []byte
)

func file_sdk_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_sdk_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_sdk_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_plugin_v1_plugin_proto_rawDesc), len(file_sdk_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_sdk_plugin_v1_plugin_proto_rawDescData
}

var file_sdk_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_plugin_v1_plugin_proto_goTypes = []any{
	(PluginType)(0),      // 0: sdk.plugin.v1.PluginType
	(*InfoRequest)(nil),  // 1: sdk.plugin.v1.InfoRequest
	(*InfoResponse)(nil), // 2: sdk.plugin.v1.InfoResponse
}
var file_sdk_plugin_v1_plugin_proto_depIdxs = []int32{
	0, // 0: sdk.plugin.v1.InfoResponse.types:type_name -> sdk.plugin.v1.PluginType
	1, // 1: sdk.plugin.v1.PluginService.Info:input_type -> sdk.plugin.v1.InfoRequest
	2, // 2: sdk.plugin.v1.PluginService.Info:output_type -> sdk.plugin.v1.InfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_plugin_v1_plugin_proto_init() }
func file_sdk_plugin_v1_plugin_proto_init() {
	if File_sdk_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_plugin_v1_plugin_proto_rawDesc), len(file_sdk_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_sdk_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_sdk_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_sdk_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_sdk_plugin_v1_plugin_proto = out.File
	file_sdk_plugin_v1_plugin_proto_goTypes = nil
	file_sdk_plugin_v1_plugin_proto_depIdxs = nil
}
