// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth/v1/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TlsCertificateDer []byte                 `protobuf:"bytes,1,opt,name=tls_certificate_der,json=tlsCertificateDer,proto3" json:"tls_certificate_der,omitempty"`
	Sni               string                 `protobuf:"bytes,2,opt,name=sni,proto3" json:"sni,omitempty"`
	RemoteAddr        string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Method            string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Path              string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Headers           map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetTlsCertificateDer() []byte {
	if x != nil {
		return x.TlsCertificateDer
	}
	return nil
}

func (x *AuthenticateRequest) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *AuthenticateRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *AuthenticateRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthenticateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuthenticateRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityName  string                 `protobuf:"bytes,1,opt,name=identity_name,json=identityName,proto3" json:"identity_name,omitempty"`
	Groups        []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetIdentityName() string {
	if x != nil {
		return x.IdentityName
	}
	return ""
}

func (x *AuthenticateResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *AuthenticateResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\fdink.auth.v1\"\xaa\x02\n" +
	"\x13AuthenticateRequest\x12.\n" +
	"\x13tls_certificate_der\x18\x01 \x01(\fR\x11tlsCertificateDer\x12\x10\n" +
	"\x03sni\x18\x02 \x01(\tR\x03sni\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12H\n" +
	"\aheaders\x18\x06 \x03(\v2..dink.auth.v1.AuthenticateRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x14AuthenticateResponse\x12#\n" +
	"\ridentity_name\x18\x01 \x01(\tR\fidentityName\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\tR\x06groups\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2j\n" +
	"\x11AuthPluginService\x12U\n" +
	"\fAuthenticate\x12!.dink.auth.v1.AuthenticateRequest\x1a\".dink.auth.v1.AuthenticateResponseB)Z'github.com/sysson/dink/sdk/auth/v1;authb\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_v1_auth_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: dink.auth.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 1: dink.auth.v1.AuthenticateResponse
	nil,                          // 2: dink.auth.v1.AuthenticateRequest.HeadersEntry
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	2, // 0: dink.auth.v1.AuthenticateRequest.headers:type_name -> dink.auth.v1.AuthenticateRequest.HeadersEntry
	0, // 1: dink.auth.v1.AuthPluginService.Authenticate:input_type -> dink.auth.v1.AuthenticateRequest
	1, // 2: dink.auth.v1.AuthPluginService.Authenticate:output_type -> dink.auth.v1.AuthenticateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
