// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sdk/auth/v1/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthZReqRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Namespace               string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	User                    string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UserAuthNMethod         string                 `protobuf:"bytes,3,opt,name=user_auth_n_method,json=userAuthNMethod,proto3" json:"user_auth_n_method,omitempty"`
	RequestMethod           string                 `protobuf:"bytes,4,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	RequestURI              string                 `protobuf:"bytes,5,opt,name=request_u_r_i,json=requestURI,proto3" json:"request_u_r_i,omitempty"`
	RequestBody             []byte                 `protobuf:"bytes,6,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	RequestHeaders          map[string]string      `protobuf:"bytes,7,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestPeerCertificates [][]byte               `protobuf:"bytes,8,rep,name=request_peer_certificates,json=requestPeerCertificates,proto3" json:"request_peer_certificates,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthZReqRequest) Reset() {
	*x = AuthZReqRequest{}
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthZReqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthZReqRequest) ProtoMessage() {}

func (x *AuthZReqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthZReqRequest.ProtoReflect.Descriptor instead.
func (*AuthZReqRequest) Descriptor() ([]byte, []int) {
	return file_sdk_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthZReqRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AuthZReqRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthZReqRequest) GetUserAuthNMethod() string {
	if x != nil {
		return x.UserAuthNMethod
	}
	return ""
}

func (x *AuthZReqRequest) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *AuthZReqRequest) GetRequestURI() string {
	if x != nil {
		return x.RequestURI
	}
	return ""
}

func (x *AuthZReqRequest) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *AuthZReqRequest) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *AuthZReqRequest) GetRequestPeerCertificates() [][]byte {
	if x != nil {
		return x.RequestPeerCertificates
	}
	return nil
}

type AuthZReqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthZReqResponse) Reset() {
	*x = AuthZReqResponse{}
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthZReqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthZReqResponse) ProtoMessage() {}

func (x *AuthZReqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthZReqResponse.ProtoReflect.Descriptor instead.
func (*AuthZReqResponse) Descriptor() ([]byte, []int) {
	return file_sdk_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthZReqResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *AuthZReqResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthZReqResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type AuthZResRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Namespace               string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	User                    string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UserAuthNMethod         string                 `protobuf:"bytes,3,opt,name=user_auth_n_method,json=userAuthNMethod,proto3" json:"user_auth_n_method,omitempty"`
	RequestMethod           string                 `protobuf:"bytes,4,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	RequestURI              string                 `protobuf:"bytes,5,opt,name=request_u_r_i,json=requestURI,proto3" json:"request_u_r_i,omitempty"`
	RequestBody             []byte                 `protobuf:"bytes,6,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	RequestHeaders          map[string]string      `protobuf:"bytes,7,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestPeerCertificates [][]byte               `protobuf:"bytes,8,rep,name=request_peer_certificates,json=requestPeerCertificates,proto3" json:"request_peer_certificates,omitempty"`
	ResponseBody            []byte                 `protobuf:"bytes,9,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseHeaders         map[string]string      `protobuf:"bytes,10,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseStatusCode      int32                  `protobuf:"varint,11,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthZResRequest) Reset() {
	*x = AuthZResRequest{}
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthZResRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthZResRequest) ProtoMessage() {}

func (x *AuthZResRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthZResRequest.ProtoReflect.Descriptor instead.
func (*AuthZResRequest) Descriptor() ([]byte, []int) {
	return file_sdk_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthZResRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AuthZResRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthZResRequest) GetUserAuthNMethod() string {
	if x != nil {
		return x.UserAuthNMethod
	}
	return ""
}

func (x *AuthZResRequest) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *AuthZResRequest) GetRequestURI() string {
	if x != nil {
		return x.RequestURI
	}
	return ""
}

func (x *AuthZResRequest) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *AuthZResRequest) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *AuthZResRequest) GetRequestPeerCertificates() [][]byte {
	if x != nil {
		return x.RequestPeerCertificates
	}
	return nil
}

func (x *AuthZResRequest) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *AuthZResRequest) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *AuthZResRequest) GetResponseStatusCode() int32 {
	if x != nil {
		return x.ResponseStatusCode
	}
	return 0
}

type AuthZResResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthZResResponse) Reset() {
	*x = AuthZResResponse{}
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthZResResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthZResResponse) ProtoMessage() {}

func (x *AuthZResResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthZResResponse.ProtoReflect.Descriptor instead.
func (*AuthZResResponse) Descriptor() ([]byte, []int) {
	return file_sdk_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthZResResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *AuthZResResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AuthZResResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_sdk_auth_v1_auth_proto protoreflect.FileDescriptor

const file_sdk_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16sdk/auth/v1/auth.proto\x12\vsdk.auth.v1\"\xb7\x03\n" +
	"\x0fAuthZReqRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12+\n" +
	"\x12user_auth_n_method\x18\x03 \x01(\tR\x0fuserAuthNMethod\x12%\n" +
	"\x0erequest_method\x18\x04 \x01(\tR\rrequestMethod\x12!\n" +
	"\rrequest_u_r_i\x18\x05 \x01(\tR\n" +
	"requestURI\x12!\n" +
	"\frequest_body\x18\x06 \x01(\fR\vrequestBody\x12Y\n" +
	"\x0frequest_headers\x18\a \x03(\v20.sdk.auth.v1.AuthZReqRequest.RequestHeadersEntryR\x0erequestHeaders\x12:\n" +
	"\x19request_peer_certificates\x18\b \x03(\fR\x17requestPeerCertificates\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x10AuthZReqResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"\xb0\x05\n" +
	"\x0fAuthZResRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12+\n" +
	"\x12user_auth_n_method\x18\x03 \x01(\tR\x0fuserAuthNMethod\x12%\n" +
	"\x0erequest_method\x18\x04 \x01(\tR\rrequestMethod\x12!\n" +
	"\rrequest_u_r_i\x18\x05 \x01(\tR\n" +
	"requestURI\x12!\n" +
	"\frequest_body\x18\x06 \x01(\fR\vrequestBody\x12Y\n" +
	"\x0frequest_headers\x18\a \x03(\v20.sdk.auth.v1.AuthZResRequest.RequestHeadersEntryR\x0erequestHeaders\x12:\n" +
	"\x19request_peer_certificates\x18\b \x03(\fR\x17requestPeerCertificates\x12#\n" +
	"\rresponse_body\x18\t \x01(\fR\fresponseBody\x12\\\n" +
	"\x10response_headers\x18\n" +
	" \x03(\v21.sdk.auth.v1.AuthZResRequest.ResponseHeadersEntryR\x0fresponseHeaders\x120\n" +
	"\x14response_status_code\x18\v \x01(\x05R\x12responseStatusCode\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x10AuthZResResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err2\xa5\x01\n" +
	"\x11AuthPluginService\x12G\n" +
	"\bAuthZReq\x12\x1c.sdk.auth.v1.AuthZReqRequest\x1a\x1d.sdk.auth.v1.AuthZReqResponse\x12G\n" +
	"\bAuthZRes\x12\x1c.sdk.auth.v1.AuthZResRequest\x1a\x1d.sdk.auth.v1.AuthZResResponseB\x93\x01\n" +
	"\x0fcom.sdk.auth.v1B\tAuthProtoP\x01Z'github.com/sysson/dink/sdk/auth/v1;auth\xa2\x02\x03SAX\xaa\x02\vSdk.Auth.V1\xca\x02\vSdk\\Auth\\V1\xe2\x02\x17Sdk\\Auth\\V1\\GPBMetadata\xea\x02\rSdk::Auth::V1b\x06proto3"

var (
	file_sdk_auth_v1_auth_proto_rawDescOnce sync.Once
	file_sdk_auth_v1_auth_proto_rawDescData []byte
)

func file_sdk_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_sdk_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_sdk_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_auth_v1_auth_proto_rawDesc), len(file_sdk_auth_v1_auth_proto_rawDesc)))
	})
	return file_sdk_auth_v1_auth_proto_rawDescData
}

var file_sdk_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sdk_auth_v1_auth_proto_goTypes = []any{
	(*AuthZReqRequest)(nil),  // 0: sdk.auth.v1.AuthZReqRequest
	(*AuthZReqResponse)(nil), // 1: sdk.auth.v1.AuthZReqResponse
	(*AuthZResRequest)(nil),  // 2: sdk.auth.v1.AuthZResRequest
	(*AuthZResResponse)(nil), // 3: sdk.auth.v1.AuthZResResponse
	nil,                      // 4: sdk.auth.v1.AuthZReqRequest.RequestHeadersEntry
	nil,                      // 5: sdk.auth.v1.AuthZResRequest.RequestHeadersEntry
	nil,                      // 6: sdk.auth.v1.AuthZResRequest.ResponseHeadersEntry
}
var file_sdk_auth_v1_auth_proto_depIdxs = []int32{
	4, // 0: sdk.auth.v1.AuthZReqRequest.request_headers:type_name -> sdk.auth.v1.AuthZReqRequest.RequestHeadersEntry
	5, // 1: sdk.auth.v1.AuthZResRequest.request_headers:type_name -> sdk.auth.v1.AuthZResRequest.RequestHeadersEntry
	6, // 2: sdk.auth.v1.AuthZResRequest.response_headers:type_name -> sdk.auth.v1.AuthZResRequest.ResponseHeadersEntry
	0, // 3: sdk.auth.v1.AuthPluginService.AuthZReq:input_type -> sdk.auth.v1.AuthZReqRequest
	2, // 4: sdk.auth.v1.AuthPluginService.AuthZRes:input_type -> sdk.auth.v1.AuthZResRequest
	1, // 5: sdk.auth.v1.AuthPluginService.AuthZReq:output_type -> sdk.auth.v1.AuthZReqResponse
	3, // 6: sdk.auth.v1.AuthPluginService.AuthZRes:output_type -> sdk.auth.v1.AuthZResResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_auth_v1_auth_proto_init() }
func file_sdk_auth_v1_auth_proto_init() {
	if File_sdk_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_auth_v1_auth_proto_rawDesc), len(file_sdk_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_sdk_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_sdk_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_sdk_auth_v1_auth_proto = out.File
	file_sdk_auth_v1_auth_proto_goTypes = nil
	file_sdk_auth_v1_auth_proto_depIdxs = nil
}
