// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: auth/v1/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthPluginService_Authenticate_FullMethodName = "/dink.auth.v1.AuthPluginService/Authenticate"
)

// AuthPluginServiceClient is the client API for AuthPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthPluginServiceClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPluginServiceClient(cc grpc.ClientConnInterface) AuthPluginServiceClient {
	return &authPluginServiceClient{cc}
}

func (c *authPluginServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AuthPluginService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPluginServiceServer is the server API for AuthPluginService service.
// All implementations must embed UnimplementedAuthPluginServiceServer
// for forward compatibility.
type AuthPluginServiceServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	mustEmbedUnimplementedAuthPluginServiceServer()
}

// UnimplementedAuthPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthPluginServiceServer struct{}

func (UnimplementedAuthPluginServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAuthPluginServiceServer) mustEmbedUnimplementedAuthPluginServiceServer() {}
func (UnimplementedAuthPluginServiceServer) testEmbeddedByValue()                           {}

// UnsafeAuthPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPluginServiceServer will
// result in compilation errors.
type UnsafeAuthPluginServiceServer interface {
	mustEmbedUnimplementedAuthPluginServiceServer()
}

func RegisterAuthPluginServiceServer(s grpc.ServiceRegistrar, srv AuthPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthPluginService_ServiceDesc, srv)
}

func _AuthPluginService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPluginService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPluginService_ServiceDesc is the grpc.ServiceDesc for AuthPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dink.auth.v1.AuthPluginService",
	HandlerType: (*AuthPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthPluginService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
